### ISSUE TITLE
Translate is not showing html any more

### ISSUE THREAD

**Issue by gdulski** [angular-slider/ng5-slider#37] opened 2018-11-12 15:27 UTC
Hi
In short... I'm using
`
"@angular/core": "^6.1.1",
"typescript": "~2.7.2",
"ng5-slider": "^1.1.4",
`

This type of code is not working any more: https://angular-slider.github.io/ng5-slider/#custom-html-display-function-slider

I'm actually try to put something like this
`<img src="${image}" alt="" />``
`
But example with `<b>` tag just shows up as a plain text. Let me know If you need any extra feedback.

Thanks in advance.

**Comment by piotrdz** [comment] 2018-11-12 18:44
It seems to be working for me, even with image tags. Could you reproduce it on StackBlitz by forking [this example](https://stackblitz.com/edit/ng5-slider-customised-range-slider-example)?

**Comment by gdulski** [comment] 2018-11-13 09:39
Ok I will double check it... maybe It's happened because of some angular configuration...

**Comment by piotrdz** [comment] 2018-11-22 09:07
@gdulski: Any update on this?

**Comment by sorabh2008** [comment] 2019-02-12 00:31
Works for me after updating to 1.1.12

**Comment by piotrdz** [comment] 2019-02-12 07:17
Since there hasn't been any update from original report and I also see nothing wrong here, I'm going to close this ticket.

**Closed by piotrdz** 2019-02-12 07:17 UTC
