### ISSUE TITLE
Range Slider Min & Max are not displayed Unless Window resize is applied

### ISSUE THREAD

**Issue by rhgithub1** [angular-slider/ng5-slider#15] opened 2018-08-14 00:43 UTC
Is there a refresh method which must be invoked for the minimum and maximum values to be set for the range slider? If I adjust the window the value gets set on the view.

**Comment by piotrdz** [comment] 2018-08-14 07:03
The slider component should be displayed correctly on first render, unless you are changing the options object programmatically, in which case the change detection may not always pick it up.

Can you provide an example of your code that reproduces this issue?

**Comment by rhgithub1** [comment] 2018-08-15 00:56
Here is my component Class

export class PersonalFilterComponent implements OnInit, AfterViewInit{
  public age: any = {};
  public minValue: number = 20;
  maxValue: number = 30;
  options: Options = {
    floor: 18,
    ceil: 55,
    step: 1
  };
   
}

HTML Snippet

 <ng5-slider  [(value)]="minValue" [(highValue)]="maxValue" [options]="options"></ng5-slider>

**Comment by piotrdz** [comment] 2018-08-16 06:37
I pasted your code into a Plunk and it seems to be working correctly:
https://plnkr.co/edit/IideE3?p=preview

**Comment by rhgithub1** [comment] 2018-08-17 00:16
thank you. I have this implemented on a child component. Does it make any difference?

**Comment by piotrdz** [comment] 2018-08-19 11:09
Thanks for the additional information. I have managed to reproduce the issue now. It's caused by applying CSS styles that change the `display` property (e.g. `none` -> `block`).

There are a few JS tricks that I could employ to detect and react to such changes, but the downside is that it would have a significant performance hit, and it would  complicate the library code, which is already very complicated.

What I can do instead, is to add an input that would trigger a refresh of the slider. It would act similarly to broadcasting `rzSliderForceRender` in angularjs-slider. It would need to be manually triggered each time but I think it's a good trade-off.

**Comment by rhgithub1** [comment] 2018-08-19 13:33
thank you @piotrdz just in time before I was thinking of using another library. Do you know how soon or late this feature maybe available? really appreciate your time spent on this!

**Comment by piotrdz** [comment] 2018-08-19 19:56
@rhgithub1 It's done now and released in v1.1.2. It was a relatively easy fix. I added an example of how to use it on Github pages: https://angular-slider.github.io/ng5-slider/#manual-refresh-slider

**Closed** 2018-08-19 19:57 UTC

**Comment by koverda** [comment] 2018-11-30 03:34
@piotrdz thank you!

**Comment by kramer9802** [comment] 2019-03-13 14:19
Is this really the answer? Put a control on the form and make the user click it to fix it. There has to be some event we can hook into and fire the refresh. Please Advise.
