### ISSUE TITLE
Tooltip not displaying data as expected

### ISSUE THREAD

**Issue by leonidasthelab** [angular-slider/ng5-slider#18] opened 2018-08-30 04:14 UTC
I am displaying a slider where the ticks are nonlinear, example: [35,1,9,15,30,33,50,65,77,99] are the tick values. Depending on the tick value, the tool tip will hold dynamically generated data through use of the ticksTooltip function provided.

I am noticing that some of the tooltips are not displaying any data on hover while some are...I have verified that the data being generated to populate the tool tip at each tick mark is not null, so the data for each tool tip should be there. Has anyone encountered this issue or any suggested fix?

Thanks!!

**Comment by piotrdz** [comment] 2018-08-30 09:40
I tried to create a reproduction example using [this Stackblitz](https://stackblitz.com/edit/ng5-slider-tooltip-issue), but it seems to be working correctly for me.

Could you post some more code or create an example with reproduction?

Also, which mechanism are you using to display tooltips? The default one, or using ng-bootstrap?

**Comment by piotrdz** [comment] 2018-09-29 22:35
@leonidasthelab  I haven't received any update or any other reports of this issue, so unless I have more information, I'm inclined to close this ticket.

**Closed** 2018-10-04 09:11 UTC
