### ISSUE TITLE
Many decimals in pushRange Slider

### ISSUE THREAD

**Issue by mkurte** [angular-slider/ng5-slider#25] opened 2018-10-08 11:10 UTC
Hi there,

first of all many thanks for your great work! I really enjoy your slider component, its great!
Lately I was creating a pushRange slider with the ng5-slider which had a step range of 0.1 and the precision parameter set to 1. I also added Textinputs to modify the values directly. Everything works like a charm except for one case. Wen I slide on pointer and the minimum range with is reached I start to push the range. Thats what I want and what the feature is. But sometimes I get some dirty numbers with very long decimals. You can see it in the attached screenshot.
Maybe it's a javascript rounding error and you can fix it with `toFixed(number of precision)` or something similar?

Thanks again a lot,
Matthias

<img width="900" alt="bildschirmfoto 2018-10-08 um 13 03 52" src="https://user-images.githubusercontent.com/1608368/46605676-a396bd80-cafa-11e8-89e8-92894924b7e1.png">

**Comment by piotrdz** [comment] 2018-10-23 07:16
Thanks for spotting this issue.

Normally, you could use `translate` function to provide your custom callback to format the numbers using `toFixed` or any other method you need.

However, in this case, the problem is that the underlying model value is calculated inaccurately, as a consequence of accumulating floating-point errors. Interestingly, the original code contained a `precision` option, and some additional code that was supposed to fix it, but it was used only in one place when calculating step array.

To fix this properly, I decided to drop the `precision` option and instead apply a new rounding function in places where model value is calculated in slider event handlers. The cut-off for rounding is given by a new option `precisionLimit`, which is by default 12 digits and it should be plenty for regular use.

I verified that your issue is no longer present after the fix. If you are happy with that solution, I'm going to close this issue.

**Comment by piotrdz** [comment] 2018-10-24 09:43
Closing as fixed with v1.1.4 ( [StackBlitz example](https://stackblitz.com/edit/ng5-slider-issue-25?file=src/app/app.component.ts) ).

**Closed by piotrdz** 2018-10-24 09:43 UTC
