### ISSUE TITLE
Change slider css style

### ISSUE THREAD

**Issue by phantomodm** [angular-slider/ng5-slider#11] opened 2018-08-01 15:22 UTC
Hello,

Quickie.. How can I change or add css attributes on the ng5-slider directive..  For example, I want to move the labels to the opposite side of slider. I can't find css in the library.. Thanks.

**Comment by piotrdz** [comment] 2018-08-31 09:58
Since there haven't been any updates on this, and the issue is more a question rather than a bug report, I'm closing this.

**Closed by piotrdz** 2018-08-31 09:58 UTC
