### ISSUE TITLE
Not getting highValue on userChange event

### ISSUE THREAD

**Issue by SuhailTanwar** [angular-slider/ng5-slider#108] opened 2019-06-10 06:46 UTC
When user changes the slider on userchange event i am not getting highValue property and instead value is returning highest value and there is no min value.

<ng5-slider [(value)]="minValue" [(highValue)]="maxValue" [options]="options"
                    (userChange)="onFilterChange($event)" (userChangeEnd)="filterChangeEnd($event)"></ng5-slider>

component-->
import { ChangeContext, Options } from 'ng5-slider';

options: Options = {
    floor: 0,
    ceil: 11,
    step: 1,
    showTicksValues: true

  };
 this.minValue = 0;
 this.maxValue = 11;

// Set filtered month list
  onFilterChange(changeContext: ChangeContext) {
    console.log("[onFilterChange] - Start");
    this.filteredMonths = [];

    for (var minVal = changeContext.value; minVal <= changeContext.highValue; minVal++) {
      var monthData = this.monthsList[minVal].legend.split(" ");
      this.filteredMonths.push(monthData[0]);
    }
    console.log('=============FILTERMONTHS==================')
    console.log(this.filteredMonths)
    this.isTwleveMonths = (this.filteredMonths.length == 12) ? true : false;

  }

**Comment by piotrdz** [comment] 2019-06-10 08:49
Thanks for reporting this. That was caused by my rewrite of this code.

I pushed a fix to master and I will release it in next version.

**Comment by SuhailTanwar** [comment] 2019-06-10 10:27
Thank You!!

**Comment by piotrdz** [comment] 2019-06-11 10:15
Fix now released in v1.2.1.

**Closed by piotrdz** 2019-06-11 10:15 UTC
Labels: accepted, bug
